// Drafter — écussons de clubs (généré par tools/scrape-logos.js)
// Ne pas éditer à la main : relance `node tools/scrape-logos.js`.
window.CLUB_LOGOS = {
  "AC Milan": "assets/logos/ac-milan.svg",
  "AS Roma": "assets/logos/as-roma.svg",
  "Al Hilal": "assets/logos/al-hilal.svg",
  "Al Nassr": "assets/logos/al-nassr.svg",
  "Al-Hilal": "assets/logos/al-hilal.svg",
  "Al-Nassr": "assets/logos/al-nassr.svg",
  "Al-Nassr FC": "assets/logos/al-nassr.svg",
  "Arsenal": "assets/logos/arsenal.svg",
  "Aston Villa": "assets/logos/aston-villa.svg",
  "Atalanta": "assets/logos/atalanta.svg",
  "Athletic Bilbao": "assets/logos/athletic-bilbao.svg",
  "Atlético Madrid": "assets/logos/atletico-madrid.svg",
  "Bayer Leverkusen": "assets/logos/bayer-leverkusen.svg",
  "Bayern Munich": "assets/logos/bayern-munich.svg",
  "Bayern München": "assets/logos/bayern-munich.svg",
  "Benfica": "assets/logos/benfica.svg",
  "Borussia Dortmund": "assets/logos/borussia-dortmund.svg",
  "Burnley": "assets/logos/burnley-fc.svg",
  "Burnley FC": "assets/logos/burnley-fc.svg",
  "Chelsea": "assets/logos/chelsea.svg",
  "Como 1907": "assets/logos/como-1907.svg",
  "Crystal Palace": "assets/logos/crystal-palace.svg",
  "FC Barcelona": "assets/logos/fc-barcelona.svg",
  "FC Porto": "assets/logos/fc-porto.svg",
  "Inter": "assets/logos/inter.svg",
  "Inter Miami": "assets/logos/inter-miami.svg",
  "Inter Miami CF": "assets/logos/inter-miami.svg",
  "Inter Milan": "assets/logos/inter.svg",
  "Internazionale": "assets/logos/inter.svg",
  "Juventus": "assets/logos/juventus.svg",
  "Lazio": "assets/logos/lazio.svg",
  "Liverpool": "assets/logos/liverpool.svg",
  "Lyon": "assets/logos/lyon.svg",
  "Manchester City": "assets/logos/manchester-city.svg",
  "Manchester United": "assets/logos/manchester-united.png",
  "Marseille": "assets/logos/marseille.svg",
  "Napoli": "assets/logos/napoli.svg",
  "Newcastle": "assets/logos/newcastle.svg",
  "Olympique Marseille": "assets/logos/marseille.svg",
  "PSG": "assets/logos/paris-sg.svg",
  "Paris SG": "assets/logos/paris-sg.svg",
  "Paris Saint-Germain": "assets/logos/paris-sg.svg",
  "Porto": "assets/logos/fc-porto.svg",
  "RB Leipzig": "assets/logos/rb-leipzig.svg",
  "Real Madrid": "assets/logos/real-madrid.png",
  "Real Sociedad": "assets/logos/real-sociedad.svg",
  "Roma": "assets/logos/as-roma.svg",
  "Sporting CP": "assets/logos/sporting-cp.png",
  "West Ham": "assets/logos/west-ham.svg",
};
