// Drafter — écussons de clubs (généré par tools/scrape-logos.js)
// Ne pas éditer à la main : relance `node tools/scrape-logos.js`.
window.CLUB_LOGOS = {
  "AC Milan": "assets/logos/ac-milan.svg",
  "AFC Bournemouth": "assets/logos/bournemouth.svg",
  "AS Monaco": "assets/logos/monaco.svg",
  "AS Roma": "assets/logos/as-roma.svg",
  "Ajax": "assets/logos/ajax-amsterdam.svg",
  "Ajax Amsterdam": "assets/logos/ajax-amsterdam.svg",
  "Al Ahli": "assets/logos/al-ahli.svg",
  "Al Hilal": "assets/logos/al-hilal.svg",
  "Al Ittihad": "assets/logos/al-ittihad.svg",
  "Al Nassr": "assets/logos/al-nassr.svg",
  "Al-Ahli": "assets/logos/al-ahli.svg",
  "Al-Hilal": "assets/logos/al-hilal.svg",
  "Al-Ittihad": "assets/logos/al-ittihad.svg",
  "Al-Nassr": "assets/logos/al-nassr.svg",
  "Al-Nassr FC": "assets/logos/al-nassr.svg",
  "Almería": "assets/logos/ud-almeria.svg",
  "Arsenal": "assets/logos/arsenal.svg",
  "Aston Villa": "assets/logos/aston-villa.svg",
  "Atalanta": "assets/logos/atalanta.svg",
  "Athletic Bilbao": "assets/logos/athletic-bilbao.svg",
  "Atlético Madrid": "assets/logos/atletico-madrid.svg",
  "Bayer Leverkusen": "assets/logos/bayer-leverkusen.svg",
  "Bayern Munich": "assets/logos/bayern-munich.svg",
  "Bayern München": "assets/logos/bayern-munich.svg",
  "Benfica": "assets/logos/benfica.svg",
  "Boca Juniors": "assets/logos/boca-juniors.svg",
  "Bologna": "assets/logos/bologna.svg",
  "Borussia Dortmund": "assets/logos/borussia-dortmund.svg",
  "Bournemouth": "assets/logos/bournemouth.svg",
  "Brentford": "assets/logos/brentford.svg",
  "Brighton": "assets/logos/brighton.svg",
  "Brighton & Hove Albion": "assets/logos/brighton.svg",
  "Burnley": "assets/logos/burnley-fc.svg",
  "Burnley FC": "assets/logos/burnley-fc.svg",
  "Celtic": "assets/logos/celtic.svg",
  "Chelsea": "assets/logos/chelsea.svg",
  "Como 1907": "assets/logos/como-1907.svg",
  "Corinthians": "assets/logos/corinthians.svg",
  "Crystal Palace": "assets/logos/crystal-palace.svg",
  "Eintracht Frankfurt": "assets/logos/eintracht-frankfurt.svg",
  "Everton": "assets/logos/everton.svg",
  "FC Barcelona": "assets/logos/fc-barcelona.svg",
  "FC Porto": "assets/logos/fc-porto.svg",
  "Fenerbahce": "assets/logos/fenerbahce.svg",
  "Fenerbahçe": "assets/logos/fenerbahce.svg",
  "Feyenoord": "assets/logos/feyenoord.svg",
  "Fiorentina": "assets/logos/fiorentina.svg",
  "Flamengo": "assets/logos/flamengo.svg",
  "Fulham": "assets/logos/fulham.svg",
  "Galatasaray": "assets/logos/galatasaray.svg",
  "Girona": "assets/logos/girona.svg",
  "Inter": "assets/logos/inter.svg",
  "Inter Miami": "assets/logos/inter-miami.svg",
  "Inter Miami CF": "assets/logos/inter-miami.svg",
  "Inter Milan": "assets/logos/inter.svg",
  "Internazionale": "assets/logos/inter.svg",
  "Juventus": "assets/logos/juventus.svg",
  "Lazio": "assets/logos/lazio.svg",
  "Leeds": "assets/logos/leeds-united.svg",
  "Leeds United": "assets/logos/leeds-united.svg",
  "Lens": "assets/logos/lens.svg",
  "Lille": "assets/logos/lille.svg",
  "Liverpool": "assets/logos/liverpool.svg",
  "Lyon": "assets/logos/lyon.svg",
  "Manchester City": "assets/logos/manchester-city.svg",
  "Manchester United": "assets/logos/manchester-united.png",
  "Marseille": "assets/logos/marseille.svg",
  "Monaco": "assets/logos/monaco.svg",
  "Napoli": "assets/logos/napoli.svg",
  "Newcastle": "assets/logos/newcastle.svg",
  "Nice": "assets/logos/nice.svg",
  "Nottingham Forest": "assets/logos/nottingham-forest.svg",
  "Olympique Marseille": "assets/logos/marseille.svg",
  "PSG": "assets/logos/paris-sg.svg",
  "PSV": "assets/logos/psv.svg",
  "PSV Eindhoven": "assets/logos/psv.svg",
  "Paris SG": "assets/logos/paris-sg.svg",
  "Paris Saint-Germain": "assets/logos/paris-sg.svg",
  "Porto": "assets/logos/fc-porto.svg",
  "RB Leipzig": "assets/logos/rb-leipzig.svg",
  "Rangers": "assets/logos/rangers.svg",
  "Real Betis": "assets/logos/real-betis.svg",
  "Real Madrid": "assets/logos/real-madrid.png",
  "Real Sociedad": "assets/logos/real-sociedad.svg",
  "Rennes": "assets/logos/rennes.svg",
  "River Plate": "assets/logos/river-plate.svg",
  "Roma": "assets/logos/as-roma.svg",
  "Sao Paulo": "assets/logos/sao-paulo.svg",
  "Sevilla": "assets/logos/sevilla.png",
  "Sporting CP": "assets/logos/sporting-cp.png",
  "Stuttgart": "assets/logos/stuttgart.svg",
  "Sunderland": "assets/logos/sunderland.svg",
  "Sunderland AFC": "assets/logos/sunderland.svg",
  "São Paulo": "assets/logos/sao-paulo.svg",
  "Torino": "assets/logos/torino.svg",
  "UD Almería": "assets/logos/ud-almeria.svg",
  "Valencia": "assets/logos/valencia.svg",
  "Villarreal": "assets/logos/villarreal.svg",
  "West Ham": "assets/logos/west-ham.svg",
  "Wolverhampton": "assets/logos/wolverhampton.svg",
  "Wolves": "assets/logos/wolverhampton.svg",
};
