// Drafter — base de joueurs (style Transfermarkt, mai 2026)
// Postes Transfermarkt : GK, CB, LB, RB, LWB, RWB, DM, CM, AM, LM, RM, LW, RW, SS, CF, ST
// value en millions d'euros

window.PLAYERS = [
  // ===== Gardiens =====
  { id: 'donnarumma', name: 'Gianluigi Donnarumma', age: 27, club: 'Manchester City', league: 'Premier League', value: 45, positions: ['GK'], former: ['Milan', 'Paris SG'] },
  { id: 'courtois',   name: 'Thibaut Courtois',     age: 33, club: 'Real Madrid', league: 'La Liga', value: 30, positions: ['GK'], former: ['Atlético Madrid', 'Chelsea'] },
  { id: 'alisson',    name: 'Alisson Becker',       age: 33, club: 'Liverpool', league: 'Premier League', value: 32, positions: ['GK'], former: ['Roma', 'Internacional'] },
  { id: 'ederson',    name: 'Ederson',              age: 32, club: 'Al-Ittihad', league: 'Saudi Pro League', value: 18, positions: ['GK'], former: ['Manchester City', 'Benfica'] },
  { id: 'maignan',    name: 'Mike Maignan',         age: 30, club: 'Chelsea', league: 'Premier League', value: 40, positions: ['GK'], former: ['Milan', 'Lille', 'Paris SG'] },
  { id: 'onana',      name: 'André Onana',          age: 30, club: 'Manchester United', league: 'Premier League', value: 28, positions: ['GK'], former: ['Inter', 'Ajax'] },
  { id: 'tertstegen', name: 'Marc-André ter Stegen',age: 33, club: 'Barcelona', league: 'La Liga', value: 22, positions: ['GK'], former: ['Mönchengladbach'] },
  { id: 'sommer',     name: 'Yann Sommer',          age: 37, club: 'Inter', league: 'Serie A', value: 6,  positions: ['GK'], former: ['Bayern', 'Mönchengladbach'] },
  { id: 'oblak',      name: 'Jan Oblak',            age: 33, club: 'Atlético Madrid', league: 'La Liga', value: 24, positions: ['GK'], former: ['Benfica'] },
  { id: 'bounou',     name: 'Yassine Bounou',       age: 35, club: 'Al-Hilal', league: 'Saudi Pro League', value: 8,  positions: ['GK'], former: ['Sevilla', 'Girona'] },

  // ===== Défenseurs centraux =====
  { id: 'vandijk',    name: 'Virgil van Dijk',      age: 34, club: 'Liverpool', league: 'Premier League', value: 25, positions: ['CB'], former: ['Southampton', 'Celtic'] },
  { id: 'rudiger',    name: 'Antonio Rüdiger',      age: 33, club: 'Real Madrid', league: 'La Liga', value: 28, positions: ['CB'], former: ['Chelsea', 'Roma'] },
  { id: 'saliba',     name: 'William Saliba',       age: 25, club: 'Arsenal', league: 'Premier League', value: 80, positions: ['CB'], former: ['Saint-Étienne', 'Marseille'] },
  { id: 'gabriel',    name: 'Gabriel Magalhães',    age: 28, club: 'Arsenal', league: 'Premier League', value: 65, positions: ['CB'], former: ['Lille'] },
  { id: 'bastoni',    name: 'Alessandro Bastoni',   age: 27, club: 'Inter', league: 'Serie A', value: 70, positions: ['CB', 'LB'], former: ['Atalanta', 'Parma'] },
  { id: 'marquinhos', name: 'Marquinhos',           age: 32, club: 'Paris SG', league: 'Ligue 1', value: 35, positions: ['CB'], former: ['Roma'] },
  { id: 'kounde',     name: 'Jules Koundé',         age: 27, club: 'Barcelona', league: 'La Liga', value: 60, positions: ['CB', 'RB'], former: ['Sevilla', 'Bordeaux'] },
  { id: 'upamecano',  name: 'Dayot Upamecano',      age: 27, club: 'Bayern Munich', league: 'Bundesliga', value: 60, positions: ['CB'], former: ['RB Leipzig', 'Salzburg'] },
  { id: 'konate',     name: 'Ibrahima Konaté',      age: 27, club: 'Liverpool', league: 'Premier League', value: 45, positions: ['CB'], former: ['RB Leipzig'] },
  { id: 'dias',       name: 'Rúben Dias',           age: 28, club: 'Manchester City', league: 'Premier League', value: 70, positions: ['CB'], former: ['Benfica'] },
  { id: 'kim',        name: 'Kim Min-jae',          age: 29, club: 'Bayern Munich', league: 'Bundesliga', value: 38, positions: ['CB'], former: ['Napoli', 'Fenerbahçe'] },
  { id: 'tomori',     name: 'Fikayo Tomori',        age: 28, club: 'Milan', league: 'Serie A', value: 28, positions: ['CB'], former: ['Chelsea'] },
  { id: 'pavard',     name: 'Benjamin Pavard',      age: 29, club: 'Inter', league: 'Serie A', value: 25, positions: ['CB', 'RB'], former: ['Bayern', 'Stuttgart'] },

  // ===== Latéraux =====
  { id: 'theo',       name: 'Theo Hernández',       age: 28, club: 'Al-Hilal', league: 'Saudi Pro League', value: 35, positions: ['LB'], former: ['Milan', 'Real Madrid', 'Atlético Madrid'] },
  { id: 'davies',     name: 'Alphonso Davies',      age: 25, club: 'Real Madrid', league: 'La Liga', value: 60, positions: ['LB'], former: ['Bayern Munich', 'Vancouver'] },
  { id: 'robertson',  name: 'Andrew Robertson',     age: 32, club: 'Liverpool', league: 'Premier League', value: 22, positions: ['LB'], former: ['Hull City', 'Dundee'] },
  { id: 'mendes',     name: 'Nuno Mendes',          age: 23, club: 'Paris SG', league: 'Ligue 1', value: 70, positions: ['LB'], former: ['Sporting CP'] },
  { id: 'grimaldo',   name: 'Álex Grimaldo',        age: 30, club: 'Bayer Leverkusen', league: 'Bundesliga', value: 35, positions: ['LB'], former: ['Benfica', 'Barcelona'] },
  { id: 'estupinan',  name: 'Pervis Estupiñán',     age: 28, club: 'Brighton', league: 'Premier League', value: 30, positions: ['LB'], former: ['Villarreal', 'Watford'] },
  { id: 'hakimi',     name: 'Achraf Hakimi',        age: 27, club: 'Paris SG', league: 'Ligue 1', value: 75, positions: ['RB'], former: ['Inter', 'Real Madrid', 'Borussia Dortmund'] },
  { id: 'trent',      name: 'Trent Alexander-Arnold',age:27, club: 'Real Madrid', league: 'La Liga', value: 70, positions: ['RB'], former: ['Liverpool'] },
  { id: 'walker',     name: 'Kyle Walker',          age: 35, club: 'Burnley', league: 'Premier League', value: 8,  positions: ['RB'], former: ['Manchester City', 'Tottenham'] },
  { id: 'dumfries',   name: 'Denzel Dumfries',      age: 30, club: 'Inter', league: 'Serie A', value: 28, positions: ['RB'], former: ['PSV', 'Heerenveen'] },
  { id: 'frimpong',   name: 'Jeremie Frimpong',     age: 25, club: 'Liverpool', league: 'Premier League', value: 45, positions: ['RB'], former: ['Bayer Leverkusen', 'Celtic'] },

  // ===== Milieux défensifs =====
  { id: 'rodri',      name: 'Rodri',                age: 29, club: 'Manchester City', league: 'Premier League', value: 130, positions: ['DM'], former: ['Atlético Madrid', 'Villarreal'] },
  { id: 'casemiro',   name: 'Casemiro',             age: 34, club: 'Manchester United', league: 'Premier League', value: 12, positions: ['DM'], former: ['Real Madrid', 'Porto'] },
  { id: 'rice',       name: 'Declan Rice',          age: 27, club: 'Arsenal', league: 'Premier League', value: 110, positions: ['DM', 'CM'], former: ['West Ham'] },
  { id: 'tchouameni', name: 'Aurélien Tchouaméni',  age: 26, club: 'Real Madrid', league: 'La Liga', value: 80, positions: ['DM', 'CB'], former: ['Monaco', 'Bordeaux'] },
  { id: 'zubimendi',  name: 'Martín Zubimendi',     age: 27, club: 'Arsenal', league: 'Premier League', value: 65, positions: ['DM'], former: ['Real Sociedad'] },
  { id: 'ugarte',     name: 'Manuel Ugarte',        age: 25, club: 'Manchester United', league: 'Premier League', value: 38, positions: ['DM'], former: ['Paris SG', 'Sporting CP'] },
  { id: 'caicedo',    name: 'Moisés Caicedo',       age: 24, club: 'Chelsea', league: 'Premier League', value: 90, positions: ['DM', 'CM'], former: ['Brighton', 'Independiente del Valle'] },

  // ===== Milieux centraux / créatifs =====
  { id: 'bellingham', name: 'Jude Bellingham',      age: 22, club: 'Real Madrid', league: 'La Liga', value: 200, positions: ['CM', 'AM'], former: ['Borussia Dortmund', 'Birmingham'] },
  { id: 'pedri',      name: 'Pedri',                age: 23, club: 'Barcelona', league: 'La Liga', value: 120, positions: ['CM', 'AM'], former: ['Las Palmas'] },
  { id: 'gavi',       name: 'Gavi',                 age: 21, club: 'Barcelona', league: 'La Liga', value: 90, positions: ['CM'], former: [] },
  { id: 'valverde',   name: 'Federico Valverde',    age: 27, club: 'Real Madrid', league: 'La Liga', value: 100, positions: ['CM', 'RM'], former: ['Deportivo'] },
  { id: 'kdb',        name: 'Kevin De Bruyne',      age: 34, club: 'Napoli', league: 'Serie A', value: 25, positions: ['AM', 'CM'], former: ['Manchester City', 'Wolfsburg', 'Chelsea'] },
  { id: 'wirtz',      name: 'Florian Wirtz',        age: 23, club: 'Liverpool', league: 'Premier League', value: 150, positions: ['AM', 'CM'], former: ['Bayer Leverkusen'] },
  { id: 'musiala',    name: 'Jamal Musiala',        age: 23, club: 'Bayern Munich', league: 'Bundesliga', value: 140, positions: ['AM', 'CM'], former: ['Chelsea (acad.)'] },
  { id: 'odegaard',   name: 'Martin Ødegaard',      age: 27, club: 'Arsenal', league: 'Premier League', value: 80, positions: ['AM'], former: ['Real Madrid', 'Real Sociedad'] },
  { id: 'bruno',      name: 'Bruno Fernandes',      age: 31, club: 'Manchester United', league: 'Premier League', value: 55, positions: ['AM', 'CM'], former: ['Sporting CP', 'Sampdoria'] },
  { id: 'olmo',       name: 'Dani Olmo',            age: 28, club: 'Barcelona', league: 'La Liga', value: 65, positions: ['AM', 'CF'], former: ['RB Leipzig', 'Dinamo Zagreb'] },
  { id: 'foden',      name: 'Phil Foden',           age: 25, club: 'Manchester City', league: 'Premier League', value: 130, positions: ['AM', 'RW', 'CM'], former: [] },
  { id: 'kroos',      name: 'Toni Kroos',           age: 36, club: 'Hamburger SV', league: 'Bundesliga', value: 6,  positions: ['CM'], former: ['Real Madrid', 'Bayern Munich'] },
  { id: 'modric',     name: 'Luka Modrić',          age: 40, club: 'Milan', league: 'Serie A', value: 4,  positions: ['CM', 'AM'], former: ['Real Madrid', 'Tottenham'] },
  { id: 'camavinga',  name: 'Eduardo Camavinga',    age: 23, club: 'Real Madrid', league: 'La Liga', value: 75, positions: ['CM', 'DM'], former: ['Rennes'] },

  // ===== Ailiers =====
  { id: 'vini',       name: 'Vinícius Júnior',      age: 25, club: 'Real Madrid', league: 'La Liga', value: 200, positions: ['LW'], former: ['Flamengo'] },
  { id: 'leao',       name: 'Rafael Leão',          age: 26, club: 'Milan', league: 'Serie A', value: 75, positions: ['LW'], former: ['Lille', 'Sporting CP'] },
  { id: 'doku',       name: 'Jérémy Doku',          age: 23, club: 'Manchester City', league: 'Premier League', value: 65, positions: ['LW', 'RW'], former: ['Rennes', 'Anderlecht'] },
  { id: 'kvara',      name: 'Khvicha Kvaratskhelia',age: 25, club: 'Paris SG', league: 'Ligue 1', value: 90, positions: ['LW'], former: ['Napoli', 'Dinamo Batumi'] },
  { id: 'salah',      name: 'Mohamed Salah',        age: 33, club: 'Liverpool', league: 'Premier League', value: 50, positions: ['RW'], former: ['Roma', 'Chelsea'] },
  { id: 'saka',       name: 'Bukayo Saka',          age: 24, club: 'Arsenal', league: 'Premier League', value: 150, positions: ['RW', 'LW'], former: [] },
  { id: 'dembele',    name: 'Ousmane Dembélé',      age: 28, club: 'Paris SG', league: 'Ligue 1', value: 80, positions: ['RW', 'LW'], former: ['Barcelona', 'Borussia Dortmund', 'Rennes'] },
  { id: 'sancho',     name: 'Jadon Sancho',         age: 26, club: 'Juventus', league: 'Serie A', value: 25, positions: ['LW', 'RW'], former: ['Manchester United', 'Borussia Dortmund'] },
  { id: 'rashford',   name: 'Marcus Rashford',      age: 28, club: 'Aston Villa', league: 'Premier League', value: 40, positions: ['LW', 'CF'], former: ['Manchester United'] },
  { id: 'nico',       name: 'Nico Williams',        age: 23, club: 'Athletic Bilbao', league: 'La Liga', value: 70, positions: ['LW', 'RW'], former: [] },
  { id: 'yamal',      name: 'Lamine Yamal',         age: 18, club: 'Barcelona', league: 'La Liga', value: 180, positions: ['RW'], former: [] },

  // ===== Attaquants =====
  { id: 'mbappe',     name: 'Kylian Mbappé',        age: 27, club: 'Real Madrid', league: 'La Liga', value: 180, positions: ['LW', 'CF', 'ST'], former: ['Paris SG', 'Monaco'] },
  { id: 'haaland',    name: 'Erling Haaland',       age: 25, club: 'Manchester City', league: 'Premier League', value: 200, positions: ['ST', 'CF'], former: ['Borussia Dortmund', 'Salzburg'] },
  { id: 'lewandowski',name: 'Robert Lewandowski',   age: 37, club: 'Barcelona', league: 'La Liga', value: 15, positions: ['ST', 'CF'], former: ['Bayern Munich', 'Borussia Dortmund'] },
  { id: 'kane',       name: 'Harry Kane',           age: 32, club: 'Bayern Munich', league: 'Bundesliga', value: 70, positions: ['ST', 'CF'], former: ['Tottenham'] },
  { id: 'osimhen',    name: 'Victor Osimhen',       age: 27, club: 'Galatasaray', league: 'Süper Lig', value: 70, positions: ['ST', 'CF'], former: ['Napoli', 'Lille'] },
  { id: 'lautaro',    name: 'Lautaro Martínez',     age: 28, club: 'Inter', league: 'Serie A', value: 95, positions: ['ST', 'CF'], former: ['Racing Club'] },
  { id: 'vlahovic',   name: 'Dušan Vlahović',       age: 26, club: 'Juventus', league: 'Serie A', value: 50, positions: ['ST', 'CF'], former: ['Fiorentina'] },
  { id: 'nunez',      name: 'Darwin Núñez',         age: 26, club: 'Al-Hilal', league: 'Saudi Pro League', value: 35, positions: ['ST', 'CF'], former: ['Liverpool', 'Benfica'] },
  { id: 'alvarez',    name: 'Julián Álvarez',       age: 26, club: 'Atlético Madrid', league: 'La Liga', value: 90, positions: ['CF', 'ST', 'RW'], former: ['Manchester City', 'River Plate'] },
  { id: 'griezmann',  name: 'Antoine Griezmann',    age: 35, club: 'Atlético Madrid', league: 'La Liga', value: 18, positions: ['SS', 'CF'], former: ['Barcelona', 'Real Sociedad'] },
  { id: 'guirassy',   name: 'Serhou Guirassy',      age: 30, club: 'Borussia Dortmund', league: 'Bundesliga', value: 50, positions: ['ST', 'CF'], former: ['Stuttgart', 'Rennes'] },
  { id: 'kolomuani',  name: 'Randal Kolo Muani',    age: 27, club: 'Tottenham', league: 'Premier League', value: 45, positions: ['CF', 'ST'], former: ['Paris SG', 'Eintracht Frankfurt'] },
  { id: 'david',      name: 'Jonathan David',       age: 26, club: 'Juventus', league: 'Serie A', value: 50, positions: ['ST', 'CF'], former: ['Lille'] },
  { id: 'gyokeres',   name: 'Viktor Gyökeres',      age: 27, club: 'Arsenal', league: 'Premier League', value: 80, positions: ['ST', 'CF'], former: ['Sporting CP', 'Coventry'] },
  { id: 'isak',       name: 'Alexander Isak',       age: 26, club: 'Liverpool', league: 'Premier League', value: 110, positions: ['ST', 'CF'], former: ['Newcastle', 'Real Sociedad'] },
];

// Slot -> postes acceptés (alignement Transfermarkt)
window.SLOT_RULES = {
  GK:  ['GK'],
  CB:  ['CB'],
  LB:  ['LB', 'LWB'],
  RB:  ['RB', 'RWB'],
  DM:  ['DM'],
  CM:  ['CM', 'DM', 'AM'],
  AM:  ['AM', 'CM'],
  LW:  ['LW', 'LM'],
  RW:  ['RW', 'RM'],
  ST:  ['ST', 'CF'],
  SS:  ['SS', 'CF', 'AM'],
};

// Formations : 11 slots
window.FORMATIONS = {
  '4-3-3': {
    label: '4-3-3',
    slots: [
      { id: 'gk',  type: 'GK',  x: 50, y: 92 },
      { id: 'lb',  type: 'LB',  x: 12, y: 72 },
      { id: 'cb1', type: 'CB',  x: 36, y: 76 },
      { id: 'cb2', type: 'CB',  x: 64, y: 76 },
      { id: 'rb',  type: 'RB',  x: 88, y: 72 },
      { id: 'cm1', type: 'CM',  x: 26, y: 50 },
      { id: 'cm2', type: 'CM',  x: 50, y: 54 },
      { id: 'cm3', type: 'CM',  x: 74, y: 50 },
      { id: 'lw',  type: 'LW',  x: 16, y: 22 },
      { id: 'st',  type: 'ST',  x: 50, y: 14 },
      { id: 'rw',  type: 'RW',  x: 84, y: 22 },
    ],
  },
  '4-4-2': {
    label: '4-4-2',
    slots: [
      { id: 'gk',  type: 'GK', x: 50, y: 92 },
      { id: 'lb',  type: 'LB', x: 12, y: 72 },
      { id: 'cb1', type: 'CB', x: 36, y: 76 },
      { id: 'cb2', type: 'CB', x: 64, y: 76 },
      { id: 'rb',  type: 'RB', x: 88, y: 72 },
      { id: 'lm',  type: 'LW', x: 12, y: 46 },
      { id: 'cm1', type: 'CM', x: 36, y: 50 },
      { id: 'cm2', type: 'CM', x: 64, y: 50 },
      { id: 'rm',  type: 'RW', x: 88, y: 46 },
      { id: 'st1', type: 'ST', x: 36, y: 16 },
      { id: 'st2', type: 'ST', x: 64, y: 16 },
    ],
  },
  '4-2-3-1': {
    label: '4-2-3-1',
    slots: [
      { id: 'gk',  type: 'GK', x: 50, y: 92 },
      { id: 'lb',  type: 'LB', x: 12, y: 72 },
      { id: 'cb1', type: 'CB', x: 36, y: 76 },
      { id: 'cb2', type: 'CB', x: 64, y: 76 },
      { id: 'rb',  type: 'RB', x: 88, y: 72 },
      { id: 'dm1', type: 'DM', x: 36, y: 56 },
      { id: 'dm2', type: 'DM', x: 64, y: 56 },
      { id: 'lw',  type: 'LW', x: 16, y: 32 },
      { id: 'am',  type: 'AM', x: 50, y: 36 },
      { id: 'rw',  type: 'RW', x: 84, y: 32 },
      { id: 'st',  type: 'ST', x: 50, y: 12 },
    ],
  },
  '3-5-2': {
    label: '3-5-2',
    slots: [
      { id: 'gk',  type: 'GK', x: 50, y: 92 },
      { id: 'cb1', type: 'CB', x: 22, y: 76 },
      { id: 'cb2', type: 'CB', x: 50, y: 78 },
      { id: 'cb3', type: 'CB', x: 78, y: 76 },
      { id: 'lm',  type: 'LW', x: 8,  y: 50 },
      { id: 'cm1', type: 'CM', x: 30, y: 54 },
      { id: 'cm2', type: 'CM', x: 50, y: 56 },
      { id: 'cm3', type: 'CM', x: 70, y: 54 },
      { id: 'rm',  type: 'RW', x: 92, y: 50 },
      { id: 'st1', type: 'ST', x: 36, y: 16 },
      { id: 'st2', type: 'ST', x: 64, y: 16 },
    ],
  },
  '3-4-3': {
    label: '3-4-3',
    slots: [
      { id: 'gk',  type: 'GK', x: 50, y: 92 },
      { id: 'cb1', type: 'CB', x: 22, y: 76 },
      { id: 'cb2', type: 'CB', x: 50, y: 78 },
      { id: 'cb3', type: 'CB', x: 78, y: 76 },
      { id: 'lm',  type: 'LW', x: 10, y: 50 },
      { id: 'cm1', type: 'CM', x: 36, y: 54 },
      { id: 'cm2', type: 'CM', x: 64, y: 54 },
      { id: 'rm',  type: 'RW', x: 90, y: 50 },
      { id: 'lw',  type: 'LW', x: 18, y: 20 },
      { id: 'st',  type: 'ST', x: 50, y: 14 },
      { id: 'rw',  type: 'RW', x: 82, y: 20 },
    ],
  },
};
